name = "heartcare-ai"
compatibility_date = "2024-01-25"

[build]
command = "npm install && npm run build"
cwd = "/"
dist = "out"

[build.upload]
format = "directory"

[site]
bucket = "./out"

[env.production]
name = "heartcare-ai-production"

[pages_build_output_dir]
value = "out"

[vars]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
