name = "heartcare-ai"
compatibility_date = "2024-01-25"

[build]
command = "npm run build"
output_dir = "out"

[env.production]
vars = { ENVIRONMENT = "production" }

[site]
bucket = "./out"

[pages]
build_output_directory = "out"
include = ["/*"]
exclude = ["/api/*"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
