name = "heartcare-ai"
compatibility_date = "2024-01-25"

[site]
bucket = "./out"

[build]
command = "npm run build"

[env.production]
vars = { ENVIRONMENT = "production" }

[[kv_namespaces]]
binding = "HEARTCARE_KV"
id = "d3554275bb0a4117b8f8dc207ab20ee2"

[vars]
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""

[pages]
directory = "out"
include = ["**/*"]
exclude = [".git/**", "node_modules/**"]

[pages.build]
command = "npm run build"
output_directory = "out"
